get http://localhost:2900/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.ZWNoZW1hbmVlQGdtYWlsLmNvbQ.cVQNplLPzIbOtic6B2gj_Kro2ccY67TGtvhIfJ-YZl4

###
post http://localhost:2900/users
Content-Type: application/json
Authorization: Bearer asd

{
    "email": "echemanee@gmail.com",
    "username": "cire",
    "password": "admin123"
}
###
get http://localhost:2900/user/eechemane29@gmail.com
Authorization: Bearer asd
###
delete http://localhost:2900/user/cl5olx73w0061h4fy73ooetwo
Authorization: Bearer asd
###
post http://localhost:2900/login
Content-Type: application/json

{
    "email": "echemanee@gmail.com",
    "password": "admin123"
}